### ISSUE TITLE
Make site easily editable by staff

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade-alpha#81]
#### Description
The Communities team has got their GitHub and HTML skills now. The slowest part of updating the Brigade site is waiting on me to pull their changes on to the server.

Can we come up with an easier system for the Communities team to rapidly make changes?

GitHub pages and JS instead of PHP? Heroku?

**Comment by mattboitan0** [comment]
I vote for Github and Jekyll - that way I wouldn't have to bug y'all about sponsor/funder changes, etc.

**Comment by ondrae** [comment]
Going with Flask and Jinja templates for the v3 version. github.com/codeforamerica/brigade

**Comment by migurski** [comment]
Sadly, I don't think it’s possible to make Jekyll, Flask apps, and Jinja templates all work together.

Dumb question: can we organize the site so that the parts that might require content editing live outside of this repository entirely? The need for Flask here seems to be the dynamic portions of the site, which I think can be scoped quite narrowly, possibly to an even deeper sub-folder than `/brigade`.

**Comment by ondrae** [comment]
Okay, here is how I set it up. On the new version of the Brigade site at http://github.com/codeforamerica/brigade

I set up auto Heroku deploys through the Heroku dashboard. Really easy. Once the travis tests pass, all commits are pushed to Heroku.

I'll tell the Communities team that they can push commits, then check their work in a few minutes. They can still submit pull requests to me if they want to review.
